### ISSUE TITLE
Unable to build to iOS from Unity 5.3.2 using ARToolkit 5.3.2 

### ISSUE THREAD

**Issue by alechko03** [artoolkit/arunity5#111]
The issue is, when i build from Unity to iOS it goes through the build process but stop around when it says stripping assemblies. The folder which i build to is blank and no Xcode project produced.
I removed folder x86_64 but no luck.

Any help would be appreciated.

<img width="182" alt="player_settings" src="https://cloud.githubusercontent.com/assets/4671310/19360933/99601a92-914e-11e6-9780-d48cdbcfa34c.png">

**Comment by alechko03** [comment]
Ok was able to build by setting **scripting backend** to Mono2x and disabling **stripping Level** thats the only way i would get an xcode project..but now i am getting a EXEC_BAD_ACCESS specifically in **showGameUi** command..

**Comment by alechko03** [comment]
Got it working!

These are the settings that work:

BUT..and a big but...

You need to dd certain instruction on what to strip in the link.xml file, this fie is in the root of your Unity project. I specifically added:

 <assembly fullname="mscorlib">
               <type fullname="System.AppDomain" preserve="fields"/>
               <type fullname="System.InvalidOperationException" preserve="fields">
                       <method signature="System.Void .ctor()"/>
               </type>
               <type fullname="System.Object" preserve="nothing">
                      <method name="Finalize"/>
               </type>
       </assembly>

It did the job.

<img width="547" alt="working settings" src="https://cloud.githubusercontent.com/assets/4671310/19391298/062ed388-91fa-11e6-81ba-ab4be9799edb.png">


Other things:

- In the Unity project in the GameObject which has your ARController script, turn of the **Use native GL texturing (if available)** 

This will fix if you don't see the camera view

As such:

<img width="280" alt="gl rendering" src="https://cloud.githubusercontent.com/assets/4671310/19391418/854a0b1a-91fa-11e6-8625-ff52380e0a78.png">

In your Xcode project:

It will come with Enable Bitcode on, you need to turn it off. You can find in build settings of your target:

![bitcode off](https://cloud.githubusercontent.com/assets/4671310/19391518/f80f3d3c-91fa-11e6-83fb-4119db316425.png)


I used the following:

Unity 5.3.2f1 <- as of this writing that is the version of Unity that works with iOS builds. 
ARToolkit 5.3.2
Xcode - Version 8.0 (8A218a)

**Comment by BoiseBaked** [comment]
We know about disabling "Use native GL texturing" and disabling a Bitcode, a problem with all new Xcode IDE versions that come down the pipe but I'm not following what you're saying here:

"You need to dd certain instruction on what to strip in the link.xml file, this fie is in the root of your Unity project. I specifically added:"

Please clarify. Thank You.

**Comment by alechko03** [comment]
Hi BoiseBaked,

Not sure why the snippet didnt go through, on Unity docs they talk about it here:

https://docs.unity3d.com/Manual/iphone-playerSizeOptimization.html

Under Stripping for IL2CPP

I added this:

<assembly fullname="mscorlib">
               <type fullname="System.AppDomain" preserve="fields"/>
               <type fullname="System.InvalidOperationException" preserve="fields">
                       <method signature="System.Void .ctor()"/>
               </type>
               <type fullname="System.Object" preserve="nothing">
                      <method name="Finalize"/>
               </type>
       </assembly>

**Comment by alechko03** [comment]
Add the mscorlib snippet

**Comment by BoiseBaked** [comment]
OK I see, your statement was intending to say: "You need to add certain instructions on what to strip and what not to strip in file named link.xml. This file is in the root of your Unity project."

And it's about the "Configuration" heading, "Scripting Backend" option which we really don't support other than the default option which I think is "Mono" because we can't possibly test every variation of Unity's configurations on all the platforms we support. But thanks. Perhaps this closed issue will help others when comes to this Unity configuration item.

**Comment by alechko03** [comment]
Yes you are right, i was not clear enough.

No prob i know what its like to be on a deadline and trying to figure these things out.

**Comment by macropp** [comment]
I was having the same problems. I went on and changed scripting backend to Mono 2, but this results in iOS telling the user that developer needs to update the app, otherwise "it may slow down your device".

So I'm gonna try @alechko03's solution. Thanks for the posts BTW.
