### ISSUE TITLE
Camera calibration - Unity - Android

### ISSUE THREAD

**Issue by Arcorme** [artoolkit/arunity5#113]
Hello,

I am currently working with Artoolkit plugin for Unity, my aim is to build for Android.
My phone target is really precise : Samsung Galaxy S7.

In order to improve the detection I wanted to make a calibration file for the phone camera, as I did for the test camera I use on my computer.
When I tried to make it with the android application "Artoolkit Camera Calibration", I did not manage to retrieve the calibration file.

My questions are :
- Is it possible to get the calibration file for the Samsung Galaxy S7 ?
- Is the calibration file specified in Unity really put in the apk and taken into account by artoolkit on Android ?
- When using the calibration app for Android I understood that a database was made of all calibration files sent, how is it integrated back to Artoolkit ?

A great thank you for your time !

Arcorme

**Comment by ThorstenBux** [comment]
Hi,

when creating a calibration with ARToolKit App the calibration is uploaded to ARTK backend. Each App created with ARTK will fetch the calibration on the first run from that server.
That behaviour will change with the release of ARToolKit 6. Till then you would need to do a manual request to the ARTK server to retrieve the calibration. 
You can look-up how that is done in the c-code here: 
https://github.com/artoolkit/artoolkit5/blob/master/lib/SRC/Video/cparamSearch.c#L778
