### ISSUE TITLE
OpenSSL version

### ISSUE THREAD

**Issue by beto0607** [artoolkit/arunity5#118]
Hello.
I can't upload my app to Play Store, I get "[...]We rejected MyApp, with package name id.myapp, for violating our Malicious Behavior or User Data policy.[...] The vulnerabilities were addressed in OpenSSL 1.02f/1.01r.[...]". 
So I need you upgrade OpenSSL.
Thank you very much.

**Comment by ThorstenBux** [comment]
Hi @beto0607,

it looks like our SSL update didn't make it into the release version yet. See here for details: https://github.com/artoolkit/artoolkit5/issues/215
