### ISSUE TITLE
genTexData tool for Unity3D doesn't create fset3 file

### ISSUE THREAD

**Issue by nattawitta** [artoolkit/arunity5#12]
Hello, I'm using ARToolKit for Unity and I'm trying to use genTexData tool to create NFT dataset. It still created fset2 file which cannot be used. Unity3D immediately crashed when I run the scene. According to latest changelog.

- "fset2" NFT dataset files have been replaced with "fset3" files throughout the toolkit.

I'm using latest version from http://www.artoolkit.org/download-artoolkit-sdk

**Comment by wallywyyoung** [comment]
Thank you for catching this! We'll test and update the package shortly.

**Comment by wallywyyoung** [comment]
Packages have been updated, and the downloads on ARToolKit.org will represent this shortly. 5.3r1
