### ISSUE TITLE
Failed to load 'Assets/Plugins/x86_64/ARWrapper.dll'!

### ISSUE THREAD

**Issue by gilbertobitt** [artoolkit/arunity5#121]
Unity 5.5.0f3 (64 bits).
OS: Windows Server 2008 R2 Enterprise.
![Error](http://i.imgur.com/lu0HAPh.png)

methods i tried.. copy redist dlls for editor folder.. and for the plugins folder tooo. 
[Method I Tried](https://github.com/artoolkit/arunity5/issues/5)

**Comment by ThorstenBux** [comment]
Hi, can you please translate the actual error message for me. 
That would be great thanks.

**Comment by gilbertobitt** [comment]
@ThorstenBux the translation is... Not possible to find specify module.

**Comment by ThorstenBux** [comment]
What platform are you targeting?
Did you check if the directory is there in the file system?

**Comment by gilbertobitt** [comment]
android.

**Comment by gilbertobitt** [comment]
i tried but i don't know where is supose to be a folder.

**Comment by ThorstenBux** [comment]
In your Unity-Project/Assets/Plugins/...
