### ISSUE TITLE
ARToolkit crashes Unity Editor

### ISSUE THREAD

**Issue by dhawalbanker** [artoolkit/arunity5#127]
#0  0x00000138a79c90 in (Unknown)
#1  0x00000156da534a in ARController::logvWriteBuf(char*, int, int)
#2  0x00000156da2e1f in ARController::logv(int, char const*, ...)
#3  0x00000156da2c94 in ARController::initialiseBase(int, int)
#4  0x000001294e0394 in  (wrapper managed-to-native) ARNativePlugin:arwInitialiseARWithOptions (int,int) + 0xd4 (0x1294e02c0 0x1294e03e4) [0x121ba6660 - Unity Child Domain]
#5  0x000001294e01f3 in  PluginFunctions:arwInitialiseAR (int,int) + 0x113 (0x1294e00e0 0x1294e0295) [0x121ba6660 - Unity Child Domain]
#6  0x000001294dfd1a in  ARController:Awake () + 0xca (0x1294dfc50 0x1294dfea2) [0x121ba6660 - Unity Child Domain]

Seems to me like ARController is doing something illegal which is not really something I can fix but the developer of ARController should look into this and fix it.

**Comment by ThorstenBux** [comment]
Hm, that error message doesn't say much.
Can you provide steps to reproduce this error?

**Comment by dhawalbanker** [comment]
This is the repro steps.
https://github.com/artoolkit/arunity5/issues/17

After the crash, I reported the issue to Unity and they too concluded the same.

**Comment by ThorstenBux** [comment]
Hi,
in that case it looks like there is a fix available and you found it. Please contribute it back via a Pull Request. 
Thank you very much.
