### ISSUE TITLE
[Add Dirty Hack] iOS Projection Matrix zero on devices [ tested on iPhone 5 and 6 ] 

### ISSUE THREAD

**Issue by namkazt** [artoolkit/arunity5#135]
Spec: Mac 10.12.2 - Xcode 8

I was install completely new Unity 5.5.0f3 and ARUnity5 fresh download from homepage.
- Open example Simple scene ( work fine on Editor )
- Build test on Device : marker is detected but it keep show log: 
QuaternionFromMatrix got zero matrix
- 3D model not display ( in here is Cube in default simplescene )

When start ArController: Projection matrix: [
all zero
]
is it case by cam parameter not right?  because i checked it auto replace my camera parameter with another 

Full: 

> 2017-01-07 11:11:21.925419 demo[1411:516401] [DYMTLInitPlatform] platform initialization successful

2017-01-07 11:11:22.118396 demo[1411:516296] -> registered mono modules 0xd6cd00

2017-01-07 11:11:22.371879 demo[1411:516296] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.

-> applicationDidFinishLaunching()

PlayerConnection initialized from /var/containers/Bundle/Application/D93DC6F5-E06F-4100-B61F-1905730C5AF9/demo.app/Data (debug = 0)

PlayerConnection initialized network socket : 0.0.0.0 55000

Multi-casting "[IP] 192.168.31.77 [Port] 55000 [Flags] 3 [Guid] 1362682658 [EditorId] 1648979660 [Version] 1048832 [Id] iPhonePlayer(iPhone-cua-Nam):56000 [Debug] 1" to [225.0.0.222:54997]...

Waiting for connection from host on [0.0.0.0:55000]...

PlayerConnection accepted from [192.168.31.13] handle:0x6

Started listening to [0.0.0.0:55000]

2017-01-07 11:11:22.781255 demo[1411:516296] Metal GPU Frame Capture Enabled

2017-01-07 11:11:22.782096 demo[1411:516296] Metal API Validation Disabled

-> applicationDidBecomeActive()

Renderer: PowerVR SGX 543

Vendor:   Imagination Technologies

Version:  OpenGL ES 2.0 IMGSGX543-128

GLES:     2

GL_OES_depth_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_comp

ression_pvrtc 

OPENGL LOG: Creating OpenGL ES 2.0 graphics device ; Context level  <OpenGL ES 2.0> ; Context handle 375066560

Initialize engine version: 5.5.0f3 (38b4efef76f0)

-------- Shader compilation failed

#version 100

#extension GL_EXT_frag_depth : enable

precision highp float;

uniform highp vec4 _ProjectionParams;

uniform highp vec4 _ZBufferParams;

uniform highp mat4 unity_CameraToWorld;

uniform highp mat4 _NonJitteredVP;

uniform highp mat4 _PreviousVP;

uniform highp sampler2D _CameraDepthTexture;

varying highp vec2 xlv_TEXCOORD0;

varying highp vec3 xlv_TEXCOORD1;

void main ()

{

  highp vec4 tmpvar_1;

  tmpvar_1 = texture2D (_CameraDepthTexture, xlv_TEXCOORD0);

  mediump vec2 tmpvar_2;

  highp vec4 tmpvar_3;

  tmpvar_3.w = 1.0;

  tmpvar_3.xyz = ((xlv_TEXCOORD1 * (_ProjectionParams.z / xlv_TEXCOORD1.z)) * (1.0/((

    (_ZBufferParams.x * tmpvar_1.x)

   + _ZBufferParams.y))));

  highp vec4 tmpvar_4;

  tmpvar_4 = (unity_CameraToWorld * tmpvar_3);

  highp vec4 tmpvar_5;

  tmpvar_5 = (_PreviousVP * tmpvar_4);

  highp vec4 tmpvar_6;

  tmpvar_6 = (_NonJitteredVP * tmpvar_4);

  highp vec2 tmpvar_7;

  tmpvar_7 = (((tmpvar_5.xy / tmpvar_5.w) + 1.0) / 2.0);

  highp vec2 tmpvar_8;

  tmpvar_8 = (((tmpvar_6.xy / tmpvar_6.w) + 1.0) / 2.0);

  tmpvar_2 = (tmpvar_8 - tmpvar_7);

  mediump vec4 tmpvar_9;

  tmpvar_9.zw = vec2(0.0, 1.0);

  tmpvar_9.xy = tmpvar_2;

  gl_FragDepthEXT = tmpvar_1.x;

  gl_FragData[0] = tmpvar_9;

}

-------- failed compiling:

fragment evaluation shader

WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported

ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

Note: Creation of internal variant of shader 'Hidden/Internal-MotionVectors' failed.

WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader

WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.

UnloadTime: 5.628291 ms

2017-01-07 11:11:24.073977 demo[1411:516296] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

2017-01-07 11:11:24.077544 demo[1411:516296] [MC] Reading from public effective user settings.

ARController (native): [info]ARWrapper::ARController::initialiseBase(): Initialising...

ARController: ARToolKit version 5.3.2 initialised.

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]Added marker (UID=0), total markers loaded: 1.

ARController: Starting AR.

ARController:StartAR()

ARController:Start()

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Render device: OpenGL ES 2.0 IMGSGX543-128, using Unity texturing.

ARController:StartAR()

ARController:Start()

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Starting ARToolKit video with vconf ''.

ARController:StartAR()

ARController:Start()

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]ARController::startRunning(): called, start running

ARController (native): [info]Setting video configuration ''.

ARController (native): [info]Settting camera parameters buffer: 176 bytes.

ARController (native): [info]Opening ARToolKit video using configuration ''.

Using default video config.

ARController: Setting ARToolKit tracking settings.

ARController:StartAR()

ARController:Start()

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

AROrigin: Found 1 markers eligible to become base marker.

AROrigin:FindMarkers()

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: UpdateAR: Waiting for ARToolKit video.

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]Opened ARToolKit video 480x360@1Bpp (AR_PIXEL_FORMAT_420f).

Using camera_para_iPhone_5_rear_640x480_0_3m.dat for device iPhone 5.

ARController (native): [info]Using internal camera parameters.

ARController (native): [info]ARController::initAR() called

ARController: UpdateAR: ARToolKit video is running. Configuring Unity scene for video.

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Video 480x360@1Bpp (AR_PIXEL_FORMAT_420f)

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**ARController: Projection matrix: [

0.00000	0.00000	0.00000	0.00000

0.00000	0.00000	0.00000	0.00000

0.00000	0.00000	0.00000	0.00000

0.00000	0.00000	0.00000	0.00000]**

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Video size 480x360 will use texture size 480x360.

ARController:CreateVideoBackgroundMesh(Int32, Int32, Int32, Int32, Color[]&, Color32[]&, Texture2D&, Material&)

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController: Scene configured for video.

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

VideoSource::updateTexture32 will use ARM NEON acceleration.

-> applicationWillResignActive()

ARController: Stopping AR.

ARController:StopAR()

ARController:OnApplicationPause(Boolean)

 

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ARController (native): [info]Closing ARToolKit video.

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)

-> applicationDidEnterBackground()ß

**Comment by namkazt** [comment]
Case by IL2CPP generate in export api arwGetProjectionMatrix and arwQueryMarkerTransformation
Don't know why it do not set back to matrix pass as parameter to those functions. I Checked matrix is calculated but after that it immediately free by il2cpp and not set back in parameter.

sorry i'm not clearly understand it so just made a quick hack on generated code to make app working. ( i'm on deadline btw ... :( ).

Dirty hack to fix that problems:

search in Bulk_Assembly-CSharp_xxx.cpp
Find : ARNativePluginStatic_arwGetProjectionMatrix_xxx Functions
//Hack: Set pointer to matrix ( add right after Native function invocation)
    for(int32_t i = 0; i < 16; i++)
    {
        ___matrix0->SetAt(i, ____matrix0_marshaled[i]);
    }

Find : ARNativePluginStatic_arwQueryMarkerTransformation
//Hack: Set pointer to matrix  ( add right after Native function invocation)
    for(int32_t i = 0; i < 16; i++)
    {
        ___matrix1->SetAt(i, ____matrix1_marshaled[i]);
    }

**Comment by macropp** [comment]
@namkazt Thanks a lot for this hack! I'm also on a deadline and this is a lifesaver. Hope we'll get a proper fix sometime in the future.
