### ISSUE TITLE
Are we limited to square markers?

### ISSUE THREAD

**Issue by Darelbi** [artoolkit/arunity5#136]
I was investigating ARToolkit as a free alternative to Vuforia, however looking at documentation seems we have only square markers, and cannot therefore use arbitrary images for AR- recognition. Is that true?

**Comment by BoiseBaked** [comment]
ARToolKit 5 supports recognizing and tracking square fiducial markers, multi-square fiducial markers, both that can embed patterns or barcodes, and model-based natural features (NFT). The big difference between ARToolKit and Vuforia is that Vuforia provides its technology through web-services and charges for access. ARToolKit is a free download SDK. There will be addition supported marker types in a later releases.

**Comment by Darelbi** [comment]
Vuforia offer the option to use web service because the cpu recognition is
slow, but it is not limited to web service. So in future update you will
add support to recognize a particular feature of a drawing without
squares?? Thats great and will save me 500€ of vuforia non-web service

Il 09 gen 2017 20:01, "John Wolf" <notifications@github.com> ha scritto:

**Comment by ThorstenBux** [comment]
Hi, just to clarify:

ARToolKit5 already supports tracking of markers that don't contain square markers. You can track something like this:
https://github.com/artoolkit/arunity5/blob/master/doc/Marker%20images/gibraltar.jpg

We call that Natural Feature Tracking (NFT) in ARTK5.

**Comment by Darelbi** [comment]
Ahh cool, that's what I needed. It is not clear from the documentation.
Then I'll go with ARToolkit5 :)

Thanks and keep on the really cool work.

2017-01-10 2:47 GMT+01:00 Thorsten Bux <notifications@github.com>:
