### ISSUE TITLE
iOS Curl Library Linking Problem

### ISSUE THREAD

**Issue by OptrixAU** [artoolkit/arunity5#147]
I've found an issue with the Curl library - when I try to build a project, it fails with linker errors when using the included curl.a file. The 'inflate' functions don't appear to be present - perhaps whoever built the library didn't include the gzip/zlib module?

Perhaps this was done because zlib is now part of XCode, but I thought it was before-hand.

Regardless, it can be resolved by adding **libz** as a library in XCode.

**Comment by BoiseBaked** [comment]
Are you developing a native iOS app or a Unity app the targets iOS?

The iOS SDK and curl dev groups keep rearranging things. To resolve the curl dependencies:
1) Open the Xcode project.
2) In the "Link Binary with Libraries" window, click the ‘+’ button to open the frameworks and libraries window.
3) Scroll down to find “libz.tbd” entry, select and highlight it. Then scroll down to find “Security.framework” and collectively select it.
4) Add both curl dependencies by clicking the “Add” button.
You may want to pull the just added dependencies to be below the “libcurl.a” entry (just to indicate to yourself that “libcurl.a has dependencies on “libz.tbd” and “Security.framework”.
