### ISSUE TITLE
ARWrapper.dll error

### ISSUE THREAD

**Issue by fingerx** [artoolkit/arunity5#15]
Unity ver:5.1.2p3 pro
system : win7 x64
artookit ver:ARUnity5-5.3r1
when import package ,open nft sample is running ok. but when build my own nft image and import Unity ,error message show"Failed to load 'Assets/Plugins/x86_64/ARWrapper.dll'" and "', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly."
![001](https://cloud.githubusercontent.com/assets/5524551/9809596/49a4043c-589c-11e5-92e1-5ee3d8679a6a.png)

**Comment by wallywyyoung** [comment]
Hey @fingerx ,

Just to confirm. You have this file in your project?
https://github.com/artoolkit/arunity5/blob/master/src/Unity/Assets/Plugins/x86_64/ARWrapper.dll

**Comment by andrew-git** [comment]
I have same problem, project contains file ARWrapper.dll in folder pointed in error

**Comment by wallywyyoung** [comment]
@fingerx Have you tried this with the 5.3.1 release? Have you tried it with the latest in the Unity Editor?

What version of the editor, and Windows, are you using? @andrew-git

**Comment by andrew-git** [comment]
First I try on latest 5.3.1, then 5.3r, 5.2.2
Unity editors 5.2.1 and 5.0.4 on win xp 
and 5.2.2 (32 and 64) on win 7.

When installing unity package 5.3.1 I saw in console "Package corrupted, deduced GUID exists but at different destination path, refusing import."

After searching I found http://forum.unity3d.com/threads/unity-5-personal-can-we-use-dlls.306635/ and http://stackoverflow.com/questions/15923595/how-to-use-a-c-dll-in-unity3d.
Using http://dependencywalker.com/ I see that ARWrapper.dll depends on ARvideo.dll, that have in dependencies mfreadwrite.dll, mf.dll that missed on win xp.
Maybe I missed something.

Could you give working project for testing? What (minimal) requirements for using arunity5
on windows and dependencies?

Thanks!

**Comment by andrew-git** [comment]
Looks like adding msvcp120.dll and msvcr120.dll on win7 solve problem.
What dependencies on winXP and minimal SP?

**Comment by wallywyyoung** [comment]
Ah! In the tools package (and I believe the editor debugs it in the beginning), but you should download the tools package from the website and install the redistributable included there.

**Comment by wallywyyoung** [comment]
Closing for now, please reopen if you have an issue. =)
