### ISSUE TITLE
Obsolete Line of code in ARController.cs

### ISSUE THREAD

**Issue by pscheich** [artoolkit/arunity5#158]
In Line 1618 in ARToolKit5-Unity/Scripts/ARController.cs is an obsolete command. m.Optimize();

Assets/ARToolKit5-Unity/Scripts/ARController.cs(11,11): Error CS0619: `UnityEngine.Mesh.Optimize()' is obsolete: `This method is no longer supported (UnityUpgradable)' (CS0619) (Assembly-CSharp)

Cheers.

**Comment by xumo** [comment]
I just commented it out and  worked correctly. 
Just read in forums that this method Optimize() from Mesh didn't do anything at all(Mesh optimization is available in editor apparently), that's why it got removed.
