### ISSUE TITLE
Building Errors Android!

### ISSUE THREAD

**Issue by gilbertobitt** [artoolkit/arunity5#163]
Description: When i just BUILD it have the same errors but it generates the APK and i install it on device via adb.. and when using BUILD AND RUN i can't even finish compiling! and i have crashes on the app sometimes when recognizes the NFT Maker!

Unity Version: 5.6.1p1

![image](https://cloud.githubusercontent.com/assets/1363635/26364251/0ee63afc-3fba-11e7-9fa7-f28a43a7d07b.png)

**Comment by ThorstenBux** [comment]
I just updated the plugin package on gitHub. Can you use the new one and test again and tell me if it still happens?

It ran on my devices like a charm with Unity 5.6.1f1

**Comment by gilbertobitt** [comment]
sill the same.. on just **build** it compiles with errors and on **Build and Run** i fail to compile!

**Comment by gilbertobitt** [comment]
i think is more about my OS than the Unity/Plugin Itself! becouse i compile on windows server 2012!

**Comment by ThorstenBux** [comment]
I never used Win Server to compile it, so I fear I'm not much help here.
