### ISSUE TITLE
unity crashes when loading mft scene from another scene

### ISSUE THREAD

**Issue by shamain** [artoolkit/arunity5#17]
Hi

I have a ar app which has a menu. From the menu when i click on the load button it asynchronously loads the mft scene. But it crahes unity. Any idea what is the cause ?. Thanks.

Note : the scene has no heavy stuff inside it just the modification of the example mft scene.

**Comment by shamain** [comment]
Hi

I managed to fix it by moving 

//Log(LogTag + "ARController.Awake())");
		#if UNITY_IOS && !UNITY_EDITOR
		ARNativePluginStatic.aruRequestCamera();
		Thread.Sleep(2000);
		#endif
		if (PluginFunctions.arwInitialiseAR(TemplateSize, TemplateCountMax)) {
			// ARToolKit version number
			_version = PluginFunctions.arwGetARToolKitVersion();
Log(LogTag + "ARToolKit version " + _version + " initialised.");
		} else {
			Log(LogTag + "Error initialising ARToolKit");
		}

from Awake method to Start method. Not its working fine. Thanks.

**Comment by wallywyyoung** [comment]
@shamain I know this is late, but thank you!
