### ISSUE TITLE
Unable to get touch event on AR 3d model in Unity

### ISSUE THREAD

**Issue by RakeshKoplodR** [artoolkit/arunity5#171]
Hi,

I have integrated ARToolkit in my Unity3d app successfully. I am able to load 3d model also on Hiro marker.
Now I want to get the touch event of loaded 3D model on marker.

If I load Cube on marker, I am able to get the touch event on that. But if I use any other 3D model (which will have different layers on it) I am unable to get the touch event on the same.

Here is my code for getting touch event:

if(Input.touchCount == 1){
  Touch touch = Input.GetTouch(0);
  Ray ray = Camera.main.ScreenPointToRay(touch.position);
  RaycastHit hit;
  if(Physics.Raycast(ray, out hit,20){
      // Code to rotate the game object. 
  }
} 

Here in above code, Physics.Raycast(ray, out hit, 20) is returning "true" if I use Cube to load on marker.
It is returning "false" if I use any other 3D models.

What I am doing wrong here. Please help me to resolve this.

**Comment by RakeshKoplodR** [comment]
@ThorstenBux please help me with this issue. I am using Unity 5.6.1f1. Please let me know if you require more information.

**Comment by tsteffelbauer** [comment]
Does your 3D model have a collider component and is its volume big enough?

**Comment by RakeshKoplodR** [comment]
Hi @tsteffelbauer, Yes it has box collider,mesh filter, mesh render.

**Comment by tsteffelbauer** [comment]
Are you near enough (20 units) or too close (camera inside the box collider)?

**Comment by RakeshKoplodR** [comment]
@tsteffelbauer, I am new to Unity. I kept 20 units and tested with Cube it is working. When I replace the Cube with any other model it is not working.

**Comment by ThorstenBux** [comment]
@RakeshKoplodR may I ask for a screenshot of your scene graph. And a log output. Or if possible a complete export of your project.

**Comment by RakeshKoplodR** [comment]
@ThorstenBus, Thank you for reply. Sure, I will send one demo app. Can you share your email ID with me.

**Comment by ThorstenBux** [comment]
thorsten@artoolkit.org

**Comment by RakeshKoplodR** [comment]
@ThorstenBux  sorry for late reply. While creating a demo app to send you, I found the solution. I was missing some settings in inspector. I am able to rotate 3D model with touch now.

Thank you for your co-operation.

**Comment by ThorstenBux** [comment]
Could you please share the solution. So that others can benefit from that as well. Thanks :)
