### ISSUE TITLE
Crash after open scene second time on low end android devices - Android - Unity 5.6.2f1

### ISSUE THREAD

**Issue by gilbertobitt** [artoolkit/arunity5#175]
some times when i exit the scene and open again on even only changing from artoolkit scene my application crashes and when i downloaded the update version of the artoolkit 5 here the small coner box don't disappear never and on the splash screen it appears!

i have this 2 erros and i don't know what to do anymore.

**Comment by ThorstenBux** [comment]
Hi @gilbertobitt,

what crashes exactly? Do you have any error logs that appear during the crash?

Regarding the little box. That will always be there in ARToolKit5 unless you implement a way around it. You can use ARToolKit6 for that. There we fixed it. Look at artoolkit.org for the download.

**Comment by gilbertobitt** [comment]
@ThorstenBux that Will be awesome but the artoolkit6 is not compatible with unity editor on Windows!

**Comment by ThorstenBux** [comment]
Yes, you are right with that for now.

Any error logs?

**Comment by gilbertobitt** [comment]
Here is the log on lognator (where error is seen) and the logcat file.
![fdfd](https://user-images.githubusercontent.com/1363635/27958274-a8595730-62f8-11e7-8fc7-5a42472454ba.png)
[yourlog.txt](https://github.com/artoolkit/arunity5/files/1130968/yourlog.txt)

**Comment by gilbertobitt** [comment]
I fixed already! thank's for the help!
