### ISSUE TITLE
How To Execute Script Start And Stop Artoolkit Controller Camera?

### ISSUE THREAD

**Issue by amirfian** [artoolkit/arunity5#177]
how to execute script can stop webcam in artoolkit unity?

this my Script. but, can't work.
using UnityEngine;
using System.Collections;

public class StartStop : MonoBehaviour {

	ARController control;

	void Start()
	{
	control = GetComponent<ARController> ();
	control.StopAR ();
	}

	public void startCmera()
	{
		control.StartAR ();
	}

	public void stopCmera()
	{
		control.StopAR();
	}
}

![screenshot 230](https://user-images.githubusercontent.com/15823272/28112031-bdc82e2a-6721-11e7-8860-c9e0c71405e4.png)

**Comment by ThorstenBux** [comment]
Hi there,

first thing is that ARController component/script has a setting called "AutoStartAR" you can use that so that ARToolKit won't start when you start your app.

Next is to have a look at https://github.com/artoolkit/arunity5/blob/master/src/Unity/Assets/ARToolKit5-Unity/Scripts/ARController.cs#L379
You should be able to use this function to start AR

and 
https://github.com/artoolkit/arunity5/blob/master/src/Unity/Assets/ARToolKit5-Unity/Scripts/ARController.cs#L768

To stop it.

If that doesn't work as expected I'd need a log output with detailed log messages.

**Comment by amirfian** [comment]
when it called still didn't work anthing. please give me little example on simple start and stop in artoolkit unity. i didn't found 2 month and project can't finish it.
![screenshot 232](https://user-images.githubusercontent.com/15823272/28144800-e78ae33a-6797-11e7-972a-5b3c9a9a8f18.png)

**Comment by ThorstenBux** [comment]
I don't have an example ready. Besides, please provide me with a log output and a description what is supposed to happen. It is hard to understand your use-case. 
Even better would be if you could provide the project.

**Comment by amirfian** [comment]
this my schema, it just for stop and start camera ar. didn't log output
![schema](https://user-images.githubusercontent.com/15823272/28146549-0b7d1eb8-67a5-11e7-8c45-abe21d10e964.png)

**Comment by ThorstenBux** [comment]
Thanks,

but that does not help me. I still don’t know what you did and what your code base is. Meaning I have no idea where it might get wrong.

You can look for more support on the forum: https://archive.artoolkit.org/community/forums/index.php <https://archive.artoolkit.org/community/forums/index.php>

Cheers

—





Thorsten Bux | Developer Advocate
thorsten.bux_c@daqri.com <mailto:thorsten.bux_c@daqri.com>




www.artoolkit.org

**Comment by amirfian** [comment]
thanks Thorsten Bux, i just want create button for stop cameraAR and start button CameraAR in unity version 5.3.2, Whether in artoolkit version 6 already have start and stop button for AR camera?

**Comment by ThorstenBux** [comment]
No it won’t.  As that is application logic and not part of the SDK.



Have a look what the Auto-start AR. does.
—





Thorsten Bux | Developer Advocate
thorsten.bux_c@daqri.com <mailto:thorsten.bux_c@daqri.com>




www.artoolkit.org

**Comment by amirfian** [comment]
AutoStartAR run for (!StartAR()) Application.Quit(); it mean if StartAR false app will force exit from process tracking. in other script when it Call it StartAR() and StopAR() it can't work and didn't process anything

**Comment by amirfian** [comment]
Sorry not i want to compare with other, i love it using artoolkit. But how to create like this with artoolkit?
Thanks Thorsten Bux,


https://developer.vuforia.com/forum/unity-extension-technical-discussion/enable-disable-cameratrackables-vuforia-5

**Comment by ThorstenBux** [comment]
@amirfian I understand what you are trying to do. But I simply don't understand why it is not working for you and which steps you took to try and make it work. I know for sure that if you Un-Tick "AutoStart AR" in the ARControler the app will start without video background and tracking. You can then manually call InitializeAR and StartAR to make it work again

**Comment by amirfian** [comment]
![screenshot 235](https://user-images.githubusercontent.com/15823272/28157251-143d297c-67e0-11e7-976e-8aa2114a98c3.png)
here my result.. error

**Comment by amirfian** [comment]
NullReferenceException: Object reference not set to an instance of an object
StartStop.CekStart () (at Assets/StartStop.cs:24)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:144)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:621)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:756)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:53)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:52)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269)
UnityEngine.EventSystems.EventSystem:Update()

```
using UnityEngine;
using System.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading;

public class StartStop : MonoBehaviour{
	
	public GameObject Artoolkit;
	ARController ARController;

	public void CekStop(){
		ARController.StopAR ();
		//Artoolkit.GetComponent<ARController> ().StopAR;

	}

	public void CekStart(){
		ARController.StartAR();
		//Artoolkit.GetComponent<ARController> ().StartAR;
		//ARController.StopAR();
	}

}
```

**Comment by ThorstenBux** [comment]
That is because you never assigned ARController. So it is 'NULL'

**Comment by ThorstenBux** [comment]
public class StartStop : MonoBehaviour{
	
	public GameObject Artoolkit;
	ARController arController;

       public Awake(){
           arController = //Here you need to look up the ARController object
       }

	public void CekStop(){
		arController.StopAR ();
	}

	public void CekStart(){
		arController.StartAR();
	}

}

**Comment by amirfian** [comment]
Thankyou Very much ThorstenBux
here Link Script 👍 https://github.com/amirfian/ArtoolkitBest/blob/master/Simple%20Code%20Start%20and%20Stop%20Artoolkit%20v.5.3.2

**Comment by ThorstenBux** [comment]
:) Remove that line as well: https://github.com/amirfian/ArtoolkitBest/blob/master/Simple%20Code%20Start%20and%20Stop%20Artoolkit%20v.5.3.2#L14

Is does nothing and is confusing

**Comment by amirfian** [comment]
thanks again. and sorry
![screenshot 236](https://user-images.githubusercontent.com/15823272/28158612-70ec38e4-67e4-11e7-90cd-b74de8b64c3a.png)

**Comment by ThorstenBux** [comment]
Happy to help 😄. I've you can share a demo of you app I'd gladly tweet about it.

**Comment by amirfian** [comment]
https://github.com/amirfian/ArtoolkitBest/blob/master/SimpleStartStopAR.unitypackage

**Comment by amirfian** [comment]
okay, wait for it ThorstenBux
