### ISSUE TITLE
Two MFT markers not working properly.

### ISSUE THREAD

**Issue by shamain** [artoolkit/arunity5#18]
i have created two distinct mft datasets and assign them seperately. But every time i play only one is getting detected for both images. I mean only one marker scene is getting activated. What is the cause for this. This happens in sampleTwoMFTmarkers scene also. thanks.

**Comment by wallywyyoung** [comment]
@shamain Thank you for this. Unfortunately, multi-page NFT is currently non-functional. If you need multi-page NFT, you'll need to revert to v5.2 for now, but be aware of the SURF licensing issues around that. http://artoolkit.org/artoolkit-licensing
