### ISSUE TITLE
Rejected by Google Play for OpenSSL vulnerabilities.

### ISSUE THREAD

**Issue by nariakiiwatani** [artoolkit/arunity5#19]
When I uploaded my app to Google Play, I got following message from them.

>Below is the list of vulnerabilities and the corresponding APK versions that were detected in your recent submission.
>
>Version 1: OpenSSL
>Next Steps
>
>Migrate your app(s) to an updated version of OpenSSL (1.0.1h, 1.0.0m, or 0.9.8za).
>Confirm your OpenSSL version via a grep:
>$ unzip -p YourApp.apk | strings | grep "OpenSSL"

I think it's similar problem to this.
http://www.artoolkit.org/community/forums/viewtopic.php?f=26&t=4610&sid=0b54f90b7eae19126f6fd35bcfa40dce

**Comment by wallywyyoung** [comment]
We're updating libSSL from the SDK layer up. Luckily this was only used to pull down camera calibration data, which isn't sensitive now that we're open source.

**Comment by wallywyyoung** [comment]
Actually this has already been merged in. New downloadable .unitypackage pending, but if you pull the repo, it's in there.
