### ISSUE TITLE
Problem camera on device android

### ISSUE THREAD

**Issue by seboes** [artoolkit/arunity5#192]
Hi,

I've some problem when I want to build an AR scene.
After installation and run my application, before splashscreen I can see a little square (top left) where I can see my camera.
After splashscreen, my screen is black and I can not interact. I need to quit and come back in application to see my camera again in a little square (top left).

My ARtoolKit version is : version 5.5.3.2
Unity Version: 2017_2 0f3
My phone : Samsmung Galaxy A3 (2016)
Android version : Android 7.0

My application builder is on windows 10, with a version of android-sdk : 27.0.1
 
Could you help me please?

Thank you!

**Comment by IsmaelNascimento** [comment]
See its: https://github.com/artoolkit/arunity5/issues/68

**Comment by seboes** [comment]
Thanks you for the answer
