### ISSUE TITLE
ARController (native): [error]Error: Failed to load marker.

### ISSUE THREAD

**Issue by pengyingyin** [artoolkit/arunity5#199]
hi all,
i have loaded the markers in the rescourse file. And assigned it to the ARmarker Script. But when i run the project. Some of the Markers fail to load, turn out that the project can't regonize those markers. And I got the errors like this. 
![image](https://user-images.githubusercontent.com/35417134/38966304-2be55a44-43b4-11e8-8b0f-3a5ab9fddc78.png)
The setting of the ARmarker Script is as follow
![image](https://user-images.githubusercontent.com/35417134/38966383-89740b56-43b4-11e8-9d84-f40376dee5ab.png)

![image](https://user-images.githubusercontent.com/35417134/38966243-d3a3c5dc-43b3-11e8-8f20-4142398d04b7.png)

Any help will be greatly appreciated.

**Comment by ThorstenBux** [comment]
Where would you have these marker scripts from?
To me it looks like you are trying to load barcode marker with ID 27. If that is the case that can be done differently.

**Comment by pengyingyin** [comment]
The marker script is from the ARtoolkit package.
The markers is from a PatternMarker developed by {dejohnso, cohen} @ cs.utah.edu. The package is in this link: https://pan.baidu.com/s/1z06qYMGp2djc6td7-M6nVg
And i have other markers created in the same way, but those markers can be loaded successfully.
![image](https://user-images.githubusercontent.com/35417134/38967222-a4f58bc6-43b8-11e8-9726-e4f6b1f37fb9.png)

**Comment by ThorstenBux** [comment]
Unless you are using our provided tools: genTexData https://github.com/artoolkitx/artoolkitx/tree/master/Source/Utilities/genTexData
or mk_patt: https://github.com/artoolkitx/artoolkitx/tree/master/Source/Utilities/mk_patt

I can't give any support. These tools are precompiled for all platforms available from artoolkitx downloads page: http://www.artoolkitx.org/docs/downloads/
