### ISSUE TITLE
Camera crashes or is Zoomed-in

### ISSUE THREAD

**Issue by nargul90** [artoolkit/arunity5#201]
I am trying to run an application I had but now a dialog shows up(for my logitech cam) after I press the start button and then Unity crashes. When I change the Video config I get a very bad zoomed-in view in the Game tab. How can I fix this camera problem ?

**Comment by ThorstenBux** [comment]
Unfortunately, I can't say what the problem is and how to solve it. If you have please provide some log output. Other than that I can only tell you that we are pushing forward on a artoolkitX plugin for Unity3D which should soon be available here: https://github.com/artoolkitx

**Comment by nargul90** [comment]
[Editor.log](https://github.com/artoolkit/arunity5/files/2038359/Editor.log)
So this is a log file after Unity crashed. And the Zoomed image after I remove the showdialog option:
![zoomed](https://user-images.githubusercontent.com/39556204/40533091-e5e3b454-6001-11e8-8587-4146b88f807e.jpg)

**Comment by ThorstenBux** [comment]
Nothing obvious

**Comment by nargul90** [comment]
@ThorstenBux  Is there another log other than Unity's crash log? If not then I guess I have to wait for the new version.

**Comment by ThorstenBux** [comment]
Might be worth to check with another camera (if you have) to see if it is only camera related.

**Comment by nargul90** [comment]
@ThorstenBux I tried it with another camera and it doesn't crash on dialog. But still the image is very zoomed in.
