### ISSUE TITLE
UI Click event not firing correctly when arwCapture is active

### ISSUE THREAD

**Issue by theoribeiro** [artoolkit/arunity5#21]
I'm using version 5.2 on Unity 5.1.2f1 on Windows 8.1, but this is also happening on other platforms as well. 
Steps to reproduce:

1 - Create a new ARToolkit Unity Project
2 - Create UI Button or Image
3 - Add event function to Pointer Click or Pointer Down event
4 - Sometimes the click works, sometimes it gets stuck as mouse pressed, sometimes it just doesn't work

I first thought that there was something wrong with the texture updating, so I commented every line that drew anything on screen. However, the click events continued not to work.

Then, I found out that if I comment out the call to PluginFunctions.arwCapture() in ARController.cs line 691, the click events start working again. This call seems to be the problem. Are there any known workarounds for this problem?

**Comment by wallywyyoung** [comment]
@theoribeiro Hm, my initial wonder is if the event is being missed due to overhead on the main thread. Have you tried threading the call to arwCapture? Have you profiled your scene for anything overly-expensive?

**Comment by theoribeiro** [comment]
@wallywyyoung The scene is pretty simple: a cube with a Standard Shader. In any case, I will profile the scene and try threading the call to arwCapture as well. I'll only be able to get back to this project by the end of the week, but I'll let you know.

**Comment by wallywyyoung** [comment]
@theoribeiro Any updates? =)

**Comment by BoiseBaked** [comment]
Not knowing much about what you're doing, if you're using XAML UI (the built-in Unity app UI front-end), for the most part, you can't call the ARTK APIs from the XAML UI main thread. You have to call the ARTK APIs from the Unity engine thread. App events can be propagated and source from either the XAML UI thread or Unity engine thread but you can't really designate which thread plays the client thread and which plays the server thread - it's complicated. It's further complicated by Windows' Task-based Asynchronous Pattern (TAP) integrated with the C# language which the app developer must abide by or else that app easily is deadlocked. It's all not for the faint of heart. It's hard and complicated. Also, for Unity for Windows Store Universal apps, your actually using the real Windows compiler when building the app. It's the real .NET C# programming language, not Unity C# script - using Unity conditional compilation symbols to separate the two because they are not the same.

**Comment by theoribeiro** [comment]
@wallywyyoung I tried threading the call to arwCapture but it crashes the app. Maybe it changes something inside a GameObject? How would you do that without crashing? 

@BoiseBaked I am not calling the ARTK API, I am just trying to use a click event triggered by the UI to print something to the console and sometimes the method gets called, sometimes the click is ignored. Another symptom of this erratic behavior is that sometimes the button stays pressed, such as if I have never released the mouse button.

**Comment by BoiseBaked** [comment]
Which UI? Please explain in detail what you're trying do. The only clue I have are two words: "Unity" and "Windows8.1"? Please detail all of the settings of the Unity Build Settings you've selected. With a Unity app targeting Universal Windows Store, you're dealing with two UI surfaces: Windows XAML and Unity engines' render output - one embedded in the other. Are you talking Unity engine sourced events or Windows sourced events?

**Comment by theoribeiro** [comment]
@BoiseBaked 
I am building a PC, Mac & Linux Standalone, targeting Windows x86_64 platform. That is my build setting. However, I tried targeting an Android platform and the same issue happened. 

What I am trying to do is to simply have a button on a canvas in front of the camera image, so I can let the user choose the 3D model he is seeing in Augmented Reality. So I created a button and set an Event Trigger on it triggering a method that, for debugging reasons, only prints something to the console. 

What happens is that when I click on the button sometimes Unity completely ignores the event, sometimes the event triggers my method and the button gets stuck in a pressed state and sometimes everything works as it should. In a sample of 30 clicks, my method got called around 12 times and ignored on the rest. 

This is only fixed if I comment out the call to arwCapture inside ARController.cs. But, of course, I have no camera image if I do that and no AR whatsoever.

**Comment by BoiseBaked** [comment]
Oh OK, I always forget about the PC Stand Alone which for Windows is really targeting the Mono platform (not using a Windows Compiler). Now I'm reeled in. So does it fail when playing the app in the Unity Editor? Or are you actually generating a Windows Desktop Unity app, running that and seeing the failure? Is your PC running a 64bit Windows 8.1 OS?

**Comment by theoribeiro** [comment]
It fails in both cases, both in the Editor and in the generated the Desktop app. It also fails when generating an Android app.

Yes my PC is running a 64bit Windows 8.1, but we also saw the same issue happen at a 64bit Windows 7 PC.

**Comment by BoiseBaked** [comment]
Same Unity version in all failure cases?

**Comment by theoribeiro** [comment]
Yes. Haven't updated our Unity installations since then. Should I update Unity and ARUnity to see if it is fixed?

**Comment by BoiseBaked** [comment]
You mentioned commenting out PluginFunctions.arwCapture() in ARController.cs which means you're trying to update one of the ARTK example apps, right? Something must be calling whatever method that is calling arwCapture(), like a Start() or Update() - which are both themselves events. If that's the case, you have event handler hogging the game loop's bandwidth. What ARTK app are you updating with a button?

**Comment by BoiseBaked** [comment]
Are you a beginner to Unity?

**Comment by theoribeiro** [comment]
I am somewhat new to Unity, but not to programming. 

I am not updating any example projects in Unity, I created a new project from scratch and added ARUnity files and scripts as recommended. However I tried doing the same with SimpleScene and also had a problem.

When the UI problem was detected, I started digging around to find out what exactly in ARUnity was causing it, since without enabling its scripts there is no problem, and I got to this specific line in ARController.cs. PluginFunctions.arwCapture() is being called inside UpdateAR, which is being called by the scripts Update() method. 

My suspicion is basically the same as yours: the call to ARUnity plugin is somehow slowing down the game loop, making it miss some mouse events. I would guess this should be fixable, I just don't know Unity well enough to propose a solution. 

I know that Qualcomm's Vuforia Unity plugin does not interfere with UI events since we tested the same setup using it, so it shouldn't be an issue.

Are you able to reproduce the problem?

**Comment by BoiseBaked** [comment]
It's not a defect. It's Unity programming issue. Some how you included a GameObject in your Unity GameObject hierarchy that includes the ARController.cs script as a component of GameObject. When the GameObject is loaded, by virtue of it's inclusion in the hierarchy, the script is loaded and the code component's Update() event is called once per game loop frame. I think before you try to integrate ARTK in your Unity app, you need to understand how the a Unity app works and is scripted. The game loop work is sliced and diced by something called coroutines (think of C# IEnumerable and the yield operator), not multiple threads. You can add the ARTK Unity scripts to the project as an asset but don't add (and enable) them as script components to your GameObject until you understand how to integrate ARTK script components. I would have to study what the arwCapture() does before I could tell you how used in Unity.

**Comment by BoiseBaked** [comment]
Actually, the correct terminology for the hierarchy of GameObject is the Scene Hierarchy. A Unity Project can have multiple scenes.

**Comment by theoribeiro** [comment]
I fully understand how the scripts are loaded and the mechanisms of Unity's Main thread and game loop. I have been messing around with Unity before trying ARTK for a few months now, so that shouldn't be a problem. 
I think that the fact that arwCapture() is somehow preventing the game loop from triggering events is a defect, and not a small one since an UI is extremely important for some people in many AR apps.

**Comment by BoiseBaked** [comment]
OK, now I think I understand what your doing. You're purposely matching up Vuforia's video capture per frame processing against the ARTK video frame capture. The latter causes the Unity game loop to drop mouse clicks. Seemingly, a call to arwCapture() interferes with Unity game loop's non-blocking user input processing of mouse clicks. To that, I can only guess a frame capture using Vuforia takes less time than a round-trip call to arwCapture(). I can imagine that at the top of the game loop, if there were more than one click event per iteration, only the latest event is processed. I don't see how the call could interfere in any other way. It's definitely something that should be looked into.

**Comment by wallywyyoung** [comment]
@theoribeiro, to confirm, you've stated you've used Vuforia, but this project has no Vuforia scripts inside of it. It is a fresh project with a fresh import of the latest ARToolKit for Unity (5.3.1 as of typing this).

Can you include a screen shot of your ARController object inspector, with all of the foldouts expanded?

**Comment by theoribeiro** [comment]
@wallywyyoung, I fully understand this. I was simply comparing the two libraries as both have Unity versions. I just tested both of them in similar scenes to see if both presented the same issue.

Here is the screen shot of the object inspector. Please let me know if there is any more information I could provide you to help diagnose the problem.

![capture](https://cloud.githubusercontent.com/assets/535036/11632624/fdc42618-9cee-11e5-8c95-5a1c251a8f43.JPG)

**Comment by wallywyyoung** [comment]
Could you copy/paste your video config string for the Windows platform?

**Comment by theoribeiro** [comment]
-device=WinDSVL <?xml version="1.0" encoding="UTF-8"?><dsvl_input><camera show_format_dialog="false" friendly_name="Lckcam" frame_width=1280 frame_height=720 frame_rate=30><pixel_format><RGB32 flip_h="true" flip_v="true" /></pixel_format></camera></dsvl_input>

**Comment by wallywyyoung** [comment]
And finally, what was the result of your profiling? Were there a lot of high-cost calls? Was arwCapture among the highest? What is your intended system?

**Comment by theoribeiro** [comment]
Basically, ARController.update() which is the method that calls arwCapture, is consuming from 97 to 99% of CPU time. However, I cannot profile how long the calls to arwCapture take using the Profiler. At least I don't know how to do that.

![capture](https://cloud.githubusercontent.com/assets/535036/11661051/092ef38e-9db7-11e5-8b9c-bd7e03286bb9.JPG)

**Comment by BoiseBaked** [comment]
I did a little reading about this topic. The capturing mouse clicks is definitely up to the underlining OS, in your case Windows 8.1 desktop. But it's up to the game engine to tell the OS whether to do unblocking mouse event processing by buffering mouse clicks or to return only the most recent mouse click. As you can see from your profile data that the frame rate is pretty low. And, according to Unity forums, mouse event handling in the update() event is troublesome in very high or very low frame rates. The only recommendation I've seen is don't have a slow frame rate. Unfortunately, many issues posted to the Unity forum go unanswered. If that is true, and the arwCapture makes up most of the long frame time (66ms according to your profile data) then arwCapture() probably should be looked at.

Did you say you tried this on previous Unity Editor versions where this issue did not occur?

BTW, you can verify that the arwCapture() call takes up most of the 66ms frame by trying this code. I don't know if Unity makes this class available on their Windows standalone Mono runtime. Code something like this in the ARController.update() event:

Classes: System.Diagnostics.Stopwatch, System.TimeSpan.

private Stopwatch stopWatch;
update()
{
stopWatch = new Stopwatch();
stopWatch.Start();
arwCapture();
TimeSpan tS = stopWatch.Elapsed;
debug.Log(tS.Milliseconds);
}

**Comment by wallywyyoung** [comment]
Closing due to age.

**Comment by theoribeiro** [comment]
Hey guys, just a new info for whoever comes back to read this. This issue only happens when using the WinDSVL device. Using DirectShow we have no problem whatsoever with mouse events, what supports BoiseBaked's theory.
