### ISSUE TITLE
3D object position is unstable

### ISSUE THREAD

**Issue by mFontoura** [artoolkit/arunity5#26]
On the unity player the object appears fast but it doesn't stop moving, even when the marker(NFT) is not moving. On the Android phone it's worst and takes longer to appear.

Tried on unity player and Android phone. ARToolkit 5.3 | Unity 5.1.3

**Comment by mFontoura** [comment]
Like this example: 
https://www.youtube.com/watch?v=OBx0xPSxyYo

**Comment by mFontoura** [comment]
The problem might not be from the plugin. The object looks unstable because the AR Camera is getting his position form the marker.

The plugin is getting the marker position from the "arwQueryMarkerTransformation" call. Even when the marker isn't moving, the coordinates retrieved from "arwQueryMarkerTransformation" are never the same.

**Comment by wallywyyoung** [comment]
@mFontoura, Have you tried calibrating your camera and using that dat file first? Please see here:
http://artoolkit.org/documentation/doku.php?id=2_Configuration:config_camera_calibration

**Comment by mFontoura** [comment]
@wallywyyoung isn't this only for webcams? What about Android phones? How do I calibrate them?

**Comment by mFontoura** [comment]
After calibrating, the tracking with the computer webcam works much better. However, for my nexus 5 the model was still shaking (not as much). I probably need to calibrate for different cameras, but how do I add different "camera_para" in the same project?

**Comment by vlgs** [comment]
You should probably look in your ARMarker properties, there's a group-menu named "Filter Option". These options will reduce unstable pose estimation.

**Comment by mFontoura** [comment]
That helps a little but with the effect of the object sliding when I move the tracker. 

The problem might be with the cameras (I'm trying with nexus 5 and tabet xpheria z3 compact). When using the unity player the tracker is found in less than a second, however on the Android devices, I need to hold the device still for 4 seconds! 

How can I change the resolution of the camera video? I think it's too low, and it's not using auto focus.

**Comment by vlgs** [comment]
Glad it helped a bit. You can call Android Camera preference activity using these few lines : 

using (AndroidJavaClass jc = new AndroidJavaClass("com.unity3d.player.UnityPlayer")) {
			AndroidJavaObject jo = jc.GetStatic<AndroidJavaObject> ("currentActivity");
			jo.Call ("launchPreferencesActivity");
		}

**Comment by mFontoura** [comment]
@vlgs on the ARController?

**Comment by vlgs** [comment]
Anywhere ! 
Actually, this bit of code is already present in ARController but is only cued when the user press the android physical option button.

**Comment by mFontoura** [comment]
Thanks you for the great help.
I was able to change the resolution, but apparently that is not the problem. It got even worse. Took even more time to find the tracker and the model shakes more also. 

I'm out of ideas. Two different android devices with the same problem and apparently I'm the only one with this problem.

**Comment by vlgs** [comment]
You're welcome !
We also noticed long NFT detection on Androïd during tests... Probably due to mobile performance.

**Comment by mFontoura** [comment]
Oh ok, that is expected then. 

But you don't have issues like the models shaking?

**Comment by vlgs** [comment]
I don't since I've been using the filter option.

How did you calibrate the camera on your android devices ? 
Too bad there is no "Camera Calibration Service" in Unity Apps.

**Comment by mFontoura** [comment]
I just used the aplication form the play store "ARToolkit Camera Calibrator"

**Comment by mFontoura** [comment]
@vlgs You mean that me using the app "ARToolkit Camera Calibrator" isn't doing anything? I thought it was using the calibration service. What other way is there to calibrate the camera on Android?

**Comment by vlgs** [comment]
The app captures data and send it to the ARToolKit lens calibration data server. I'm not sure applications built with Unity fetch the server and use this calibration service data.

**Comment by philip-lamb** [comment]
Yes, they do.

**Comment by vlgs** [comment]
Thanks @philip-lamb

**Comment by wallywyyoung** [comment]
Yes, the "ARToolKit Camera Calibrator" is the correct app to use, and those parameters do go all the way through to our Unity plugin.

The largest impact on making your NFT marker stable is having a good camera calibration.
If you're still noticing jitter, I'd recommend using filtering to reduce noise.

You can also try different markers, with more contrast or a better distribution of features.

Closing for now, if you have any issues, feel free to open another ticket. =)

**Comment by dhawalbanker** [comment]
@wallywyyoung , @mFontoura , @vlgs @philip-lamb @arthurgiroux How can I used camera calibration for iOS device? I have Unity 5.4.0f3 (not pro). 

I have camera_para from ARToolKit package for iOS but while running on iPad Air, the code overrides it with iPhone_rear parameters. I am sending correct parameter. 

Selected log::
ARController: Starting ARToolKit video with vconf ' -format=BGRA camera_para-iPad Air 2 rear 640x480 macro'.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Camera Para = camera_para-iPad Air 2 rear 640x480 macro
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

ARController (native): [info]ARController::startRunning(): called, start running
ARController (native): [info]Setting video configuration ' -format=BGRA'.
ARController (native): [info]Settting camera parameters buffer: 176 bytes.
ARController (native): [info]Opening ARToolKit video using configuration ' -format=BGRA'.
Using supplied video config " -format=BGRA".
Requesting images in BGRA format.
ARController: Setting ARToolKit tracking settings.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

ARController: UpdateAR: Waiting for ARToolKit video.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

ARController (native): [info]Opened ARToolKit video 480x360@4Bpp (AR_PIXEL_FORMAT_BGRA).
Using camera_para_iPhone_5_rear_640x480_0_3m.dat for device iPad Air.
ARController (native): [info]Using internal camera parameters.
ARController (native): [info]ARController::initAR() called
ARController (native): [info]Marker 0 now visible
ARController: UpdateAR: ARToolKit video is running. Configuring Unity scene for video.

**Comment by dhawalbanker** [comment]
Any update on this will be highly appreciated .

**Comment by AlainOUYANG** [comment]
Is there any way to get the coordinate of the tracked marker (the coordinate on the screen)?
