### ISSUE TITLE
black margin in iOS project.

### ISSUE THREAD

**Issue by zhaiq** [artoolkit/arunity5#28]
When I try to run the unity demo in iPhone6, the screen has two black margins in up and bellow area, how to solve this?
![iphone6_black_margin](https://cloud.githubusercontent.com/assets/10611603/10963443/731eb7c0-83db-11e5-932a-3e992a20df6e.png)

**Comment by wallywyyoung** [comment]
Hello, you're running with "Content Mode: Fit" on your ARController object. Different modes allow you to display the video scaling differently.
