### ISSUE TITLE
Galaxy S6 rendering issue.

### ISSUE THREAD

**Issue by MRWUT4** [artoolkit/arunity5#31]
The Galaxy S6 does not render the given scene properly. Marker detection works, But the marker scene stays mostly invisible. The issue is described in the following forum thread:
http://artoolkit.org/community/forums/viewtopic.php?f=28&t=4608&p=7683&hilit=unity+galaxy+s6#p7683

The rendering problem appears to be simmilar to a native Android issue from 2012:
http://artoolkit.org/community/forums/viewtopic.php?f=26&t=1579&p=3030&hilit=unity+galaxy+s6#p3030

**Comment by wallywyyoung** [comment]
Could give screenshots of your ARController object, as well as your main camera with the ARCamera script on it? Are you using the stock scene in the forum post, or a modified scene of your own? Can I also ask for logcat output as well?

**Comment by MRWUT4** [comment]
A screenshot of the simple scene with a new marker object. Everything else is unmodified.
![screenshot_2015-11-24-09-54-12](https://cloud.githubusercontent.com/assets/139588/11622364/7d89143c-9cc5-11e5-8358-814807675114.png)

**Comment by wallywyyoung** [comment]
That projection seems very off. Have you ran your phone through ARToolKit's Camera Calibrator app? You may have a regional variant of your device which isn't in our database.

https://play.google.com/store/apps/details?id=com.artoolworks.ar.utils.calib_camera&hl=en
http://artoolkit.org/documentation/doku.php?id=4_Android:android_camera_calibration

**Comment by wallywyyoung** [comment]
Also, if I could still get your LogCat output, and a screenshot of your ARController object.

**Comment by MRWUT4** [comment]
We used the Camera Calibrator app, but the error persited. The screenshot was taken from a Galaxy S6 Edge. The demo works fine with the "regular" S6. The ArController screenshot:
![bildschirmfoto 2015-12-07 um 17 08 12](https://cloud.githubusercontent.com/assets/139588/11631988/26f9e110-9d05-11e5-9374-175a384e34fe.png)
Unfortunately I don't have the S6 Edge at hand. But I'll try to get a hold of the LogCat output.

**Comment by MRWUT4** [comment]
It appears to be a camera resolution problem. If we switch the camera to a 16x9 ratio resolution the projection works fine. It fails with every 4x3 ratio.

**Comment by wallywyyoung** [comment]
Good to know.

A camera calibration is good per aspect ratio- calibrating at 4:3 will product a different calibration than 16:9, because you're using a different sub-selection of the CMOS sensor, and therefore seeing through a different portion of your camera lens.

If you calibrate your device at 4:3 on the calibrator app, it may "just work".

**Comment by wallywyyoung** [comment]
Closing due to age.
