### ISSUE TITLE
iOS captured image show in screen is warped while select the 'fill' mode.

### ISSUE THREAD

**Issue by bbiirrdd** [artoolkit/arunity5#33]
Hi,
    when I export a iOS Unity project with the 'fit' mode, the captured image is right but there are two black banners upside and downside the screen, but when I re-export the project with 'fill' mode, two black banners are disappeared(image is fill with the screen), but when I rorate my iOS device, I saw the captured frame is warped, Could anyone tell me how to solve this problem? thanks.

**Comment by wallywyyoung** [comment]
Hello @bbiirrdd! Video plane setup is handled within ARController.cs. The easiest way to not encounter these stretching issues in the short-term is, however, to lock your app as a portrait or landscape app. Dynamic handling of the background on rotation would be a great addition to the toolkit (if you're up to it =) ).

**Comment by wallywyyoung** [comment]
Closing due to age.
