### ISSUE TITLE
iOS Compile Issues: Unity 5.3.1

### ISSUE THREAD

**Issue by mobyjames** [artoolkit/arunity5#40]
I'm seeing about a dozen errors related to obsolete functions calls, such as GetNativeTextureID, which are preventing project export. I'm in the process of hand-fixing them, but wanted to make sure you guys knew.

**Comment by mobyjames** [comment]
Turns out this was not actually the issue preventing export, but should probably be updated regardless.

**Comment by wallywyyoung** [comment]
Absolutely, @mobyjames! 

If you've happened to have already have fixed them, I would certainly appreciate a pull request!

**Comment by wallywyyoung** [comment]
Closing dude to issue status.
