### ISSUE TITLE
unity 5.1.1f1(64 and 32) crashs 

### ISSUE THREAD

**Issue by meeez** [artoolkit/arunity5#41]
unity 5.1.1f1(64 and 32) crashs when importing ARToolkit package to already made up scene

**Comment by wallywyyoung** [comment]
Hello Meez!

Could I get more information?

What is an "already made up scene"? What operating system are you using? Are you upgrading from a previous version of ARToolKit?

**Comment by meeez** [comment]
please check this thread !

http://artoolkit.org/community/forums/viewtopic.php?f=28&t=4827&p=8181#p8181

**Comment by ThorstenBux** [comment]
Looking at the link it looks like this issue is solved, so I close it now.
