### ISSUE TITLE
Importing into an existing Project Destroys Existing Layers

### ISSUE THREAD

**Issue by kurtquinn** [artoolkit/arunity5#45]
Hi, I just imported ARUnity5.unitypackage into my existing project to add AR functionality to it, and the package destroyed and overwrote my existing layers with it's own.  Regrettably the Unity Project File that stores the layer info was not Tracked by Git, so I have to go back rebuild all my game's layers.  I understand why you want the ARBackground and ARForeground layers there to make it easier to get started, but I don't think it's a safe assumption that everyone will be importing your package into an empty project.

**Comment by kurtquinn** [comment]
It also removed all my scenes from the build list and replaced them with your CubeMarker Scene

**Comment by wallywyyoung** [comment]
@kurtquinn I'm sorry to hear that! That is strange. Unfortunately, that's really an issue with Unity's package system. We can look into ways around this, but we didn't tell Unity to destroy your layers.

**Comment by wallywyyoung** [comment]
There is a "TagManager.asset" asset you can disable on import.
