### ISSUE TITLE
android: Attempting to load library: ARWrapper error

### ISSUE THREAD

**Issue by ckelsel** [artoolkit/arunity5#48]
HI,

**Environment**
unity3d: 5.3.2f
pkg: ARUnity5-5.3.1.unitypackage

**Problem**:
i build and install simpleScene for android, while i run the app, BREAKDOWN!
From LogCat, shows that LoadLibrary ARWrapper failed, 

here is the log from LogCat:

01-30 14:48:04.771: I/NativeInterface(15440): Attempting to load library: ARWrapper
01-30 14:48:04.771: D/dalvikvm(15440): Trying to load lib /mnt/asec/com.Artoolkit.demo-1/lib/libc++_shared.so 0x42014b18
01-30 14:48:04.776: D/dalvikvm(15440): Added shared lib /mnt/asec/com.Artoolkit.demo-1/lib/libc++_shared.so 0x42014b18
01-30 14:48:04.776: D/dalvikvm(15440): No JNI_OnLoad found in /mnt/asec/com.Artoolkit.demo-1/lib/libc++_shared.so 0x42014b18, skipping init
01-30 14:48:04.776: D/dalvikvm(15440): No JNI_OnLoad found in /system/lib/libcrypto.so 0x42014b18, skipping init
01-30 14:48:04.776: D/dalvikvm(15440): No JNI_OnLoad found in /system/lib/libssl.so 0x42014b18, skipping init
01-30 14:48:04.776: W/dalvikvm(15440): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/artoolkit/ar/unity/CameraSurface;
01-30 14:48:04.776: D/AndroidRuntime(15440): Shutting down VM
01-30 14:48:04.776: W/dalvikvm(15440): threadid=1: thread exiting with uncaught exception (group=0x4154a300)
01-30 14:48:04.781: E/AndroidRuntime(15440): FATAL EXCEPTION: main
01-30 14:48:04.781: E/AndroidRuntime(15440): java.lang.Error: FATAL EXCEPTION [main]
01-30 14:48:04.781: E/AndroidRuntime(15440): Unity version     : 5.3.2f1
01-30 14:48:04.781: E/AndroidRuntime(15440): Device model      : Meizu M040
01-30 14:48:04.781: E/AndroidRuntime(15440): Device fingerprint: Meizu/meizu_mx2/mx2:4.1.1/JRO03H/m04x.Flyme_OS_2.5.2.12328:user/release-keys
01-30 14:48:04.781: E/AndroidRuntime(15440): Caused by: java.lang.ExceptionInInitializerError
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at org.artoolkit.ar.unity.UnityARPlayerActivity.onResume(UnityARPlayerActivity.java:153)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at com.lbe.client.zz.ba.callActivityOnResume(InstrumentationDelegate.java:135)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.Activity.performResume(Activity.java:5217)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2636)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2674)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2140)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.ActivityThread.access$700(ActivityThread.java:131)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.os.Looper.loop(Looper.java:137)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at android.app.ActivityThread.main(ActivityThread.java:4866)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at dalvik.system.NativeStart.main(Native Method)
01-30 14:48:04.781: E/AndroidRuntime(15440): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load curl: findLibrary returned null
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at java.lang.Runtime.loadLibrary(Runtime.java:365)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at java.lang.System.loadLibrary(System.java:535)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at org.artoolkit.ar.base.NativeInterface.loadNativeLibrary(NativeInterface.java:74)
01-30 14:48:04.781: E/AndroidRuntime(15440): 	at org.artoolkit.ar.unity.CameraSurface.<clinit>(CameraSurface.java:70)

**Comment by wallywyyoung** [comment]
Hello @ckelsel! This has been fixed in the latest ARToolKit for Unity 5.3.2r2. Let me know if you have any other issues.

**Comment by dhawalbanker** [comment]
@wallywyyoung The latest download from ARToolKit site is still Unity 5.3.2, I am not able to find r2. Can you please point me where can I find r2?
