### ISSUE TITLE
ARWrapper.dll load fail

### ISSUE THREAD

**Issue by Briksins** [artoolkit/arunity5#5]
ARToolKit for Unity doesnt work anymore at all.
On launch it shows the fallowing exceptions:

1)
Failed to load 'Assets/Plugins/x86_64/ARWrapper.dll' with error 'The operation completed successfully.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.
ARController:OnDestroy() (at Assets/ARToolKit5-Unity/ARController.cs:443)
ARController:OnDestroy() (at Assets/ARToolKit5-Unity/ARController.cs:438)

2)
Failed to load 'Assets/Plugins/x86_64/ARWrapper.dll' with error 'The operation completed successfully.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.
PluginFunctions:arwShutdownAR() (at Assets/ARToolKit5-Unity/PluginFunctions.cs:105)
PluginFunctions:arwShutdownAR() (at Assets/ARToolKit5-Unity/PluginFunctions.cs:102)
ARController:OnDestroy() (at Assets/ARToolKit5-Unity/ARController.cs:438)

3)
DllNotFoundException: Assets/Plugins/x86_64/ARWrapper.dll
PluginFunctions.arwShutdownAR () (at Assets/ARToolKit5-Unity/PluginFunctions.cs:102)
ARController.OnDestroy () (at Assets/ARToolKit5-Unity/ARController.cs:438)

Please advise how to fix it

**Comment by r0bbie** [comment]
Was experiencing this myself. Just created a new pull request which I believe resolves it.

See https://github.com/artoolkit/arunity5/pull/7 and in particular commit https://github.com/artoolkit/arunity5/commit/03108859a42bfdfe66a4478318cf4d81b520fa48

**Comment by wallywyyoung** [comment]
Hey Guys, thank you both!

@r0bbie, would love to bring your pull in soon- working on reviewing. I have a few initial comments on the PR. =)

**Comment by bysreg** [comment]
i have tried the latest revision, the one that already has #7 . I still experience this problem. I use Unity 5.1.2f1 personal. Do I need the pro edition ? i am under the impression that the functionalities of professional and personal is the same for unity 5

**Comment by wallywyyoung** [comment]
Previously, Unity required the Professional version for native plugins. We're currently testing the free edition of 5 to see if it will work with our software. I'll keep you posted of our results!

**Comment by bysreg** [comment]
it does not work on unity 5.0.2f1 and 5.1.2f1. I will try to use the same unity version like @r0bbie do (still downloading), hopefully it will work on that version.

**Comment by r0bbie** [comment]
@bysreg Are you using the Unity Editor on Windows by any chance? If so it could perhaps be the issue described here (with fix) - http://artoolkit.org/documentation/doku.php?id=6_Unity:unity_on_windows

The files you need to copy are located in the redist or redist64 folders in the Project root.

**Comment by bysreg** [comment]
@r0bbie Thanks! it fixed it. 

before i tried your suggestion, i tried using unity 5.0.2f1 32 bit editor. and i can get it to work. it seems that the dll is not copied to the 64 bit editor counter part (the dll exists only in the 32 bit editor folder). Could it be the installer assume that if there is a 32 bit editor, that means there is no 64 bit editor ? because it is possible to have both, and also my computer has multiple versions of unity. for old and new project.

**Comment by stevenjt** [comment]
I was having this issue too and fixed it by moving the redist/redist64 DLLs to the plugin folders in the project (created a pull request #9)

**Comment by wallywyyoung** [comment]
Should be fixed in latest version!

**Comment by mojtabahanaei** [comment]
64 bit no run

**Comment by mojtabahanaei** [comment]
helping 64bit

**Comment by mojtabahanaei** [comment]
توف تو روح هر چی یونیتی
