### ISSUE TITLE
Crash on import Unity 5.0.3f2

### ISSUE THREAD

**Issue by isaacgoodfellow** [artoolkit/arunity5#52]
Downloaded the distribution from the (main webpage)[http://www.artoolkit.org/documentation/doku.php?id=6_Unity:unity_about] and can import and create working AR scenes in 5.3.0f4. However cannot import to Unity 5.0.3f2. Doing so causes a crash after selecting which parts of the package to use. At first I thought this was user error, but in the requirements I see listed that it should work back to some versions of Unity 4.

System I'm running on is running windows 7 with 8 gigs of ram.

**Comment by wallywyyoung** [comment]
Hello @isaacgoodfellow! Can you supply logs? Also, what is your need for going back so many versions?

**Comment by isaacgoodfellow** [comment]
Hey @wallywyyoung , I'm fairly new to unity, if you can walk me through what logs you want I'd be more than happy to supply them!

I was using 5.0.3f2 because I am working on a modification to a legacy project that uses a plugin whose license did not carry to the newest version. I've thankfully been able to resolve this and I'm using the current version of unity with AR toolkit just fine.

**Comment by ThorstenBux** [comment]
Hi @isaacgoodfellow ,

I'm closing this issue as it looks like everything works well for you. 
Feel free to ping this issue again if I'm wrong.

**Comment by ghonche-yqr** [comment]
Package corrupted, deduced GUID exists but at different destination path, refusing import.

how to deal with this error while importing ARToolkit Unity package into Unity 3D???????
