### ISSUE TITLE
How to open camera without dialog in windows

### ISSUE THREAD

**Issue by xiajiaonly** [artoolkit/arunity5#55]
I want to open camera with 1024 x 768,whitout dialog in widows.how to do it.
I use:-device=WinDS -width=1024 -height=768 -flipV ,it work
fail,the camera open fail.

**Comment by philip-lamb** [comment]
Overriding the defaults as you have done should work. Can you explain what you mean by "fail,the camera open fail.".

**Comment by xiajiaonly** [comment]
![image](https://cloud.githubusercontent.com/assets/4102643/14072062/8e9f14ca-f4ee-11e5-8f40-4c91f23bd5ad.png)
![image](https://cloud.githubusercontent.com/assets/4102643/14072073/ac1221d2-f4ee-11e5-8472-a4b82ce13f00.png)
UnityUnity3Dversion is 5.3.1f1

**Comment by ThorstenBux** [comment]
Hi,

I'm running Unity 5.3.4f1 with the ARToolKit for Unity version 5.3.1r2 on a Windows 10 machine. I added the same settings as in your first picture and ran the SimpleScene. It all worked straight away without any error message.

Can you maybe update Unity and see what happens.

(Couldn't test with your Unity version as I had already updated.)

**Comment by xiajiaonly** [comment]
Really! My project is in development, if now upgrade version of unity3D it may lead to disaster......T.T

**Comment by xiajiaonly** [comment]
![image](https://cloud.githubusercontent.com/assets/4102643/14134334/0b8328a0-f689-11e5-8f02-63fed5c304f3.png)

**Comment by ThorstenBux** [comment]
Hi, I could reproduce it with the help of your last screenshot. (Which I cannot see here but I have it in my mail). Could you please (just to ensure that you have the same behaviour) remove 'width and hight' from the field so that it only states '-device=WinDS -flipV'. With this setting it is running on my machine. When I enter width and height I get the same error.

**Comment by xiajiaonly** [comment]
Only with “-device=WinDS -flipV” it's worked as the default width and height(640x480).But i want to set the camera width and height with (1920x1080 or other pixels).My camera is Logitech C920.The result is the same in the version of 5.3.4f1.My OS is windows8.1 64bits.

**Comment by ThorstenBux** [comment]
ok, 
adding width and height when using -device=WinDS is not supported (http://artoolkit.org/documentation/doku.php?id=2_Configuration:config_video_capture). You can use -device=WinMF (Windows Media Foundation) instead. When using WinMF you need to set:
-format=BGRA
the following works for me:
-device=WinMF -format=BGRA -width=1920 -height=1080

(I installed Windows SDK prior to testing this, you might need to install it too; https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk)

Tell me if that works for you

**Comment by xiajiaonly** [comment]
Thank you very much.
It work well.
I did not install that SDK.
