### ISSUE TITLE
UnityEditor.DockArea.OnGUI () NullReferenceException: Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by ashokbugude** [artoolkit/arunity5#56]
ARToolkit works fine in unity in normal screen mode. 
But when I do 'maximise on Play' I get below error

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.DockArea.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:264)
ARNativePlugin:arwStartRunningB(String, Byte[], Int32, Single, Single)
PluginFunctions:arwStartRunningB(String, Byte[], Int32, Single, Single) (at Assets/ARToolKit5-Unity/Scripts/PluginFunctions.cs:114)
ARController:StartAR() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:585)

Please help me resolving it

**Comment by ThorstenBux** [comment]
Hi,

I tried and ran the sample project in `maximise on Play`. Worked fine for me. Which Unity version are you using and on which OS?
Also is it maybe possible to get the unity project that causes the error?

Thanks

**Comment by ashokbugude** [comment]
Hi ,
Its working fine now, not sure why it happened that way earlier.

**Comment by ashokbugude** [comment]
Hi ,
Thanks for your response
Its working fine today , not sure why it was throwing errors earlier

**Comment by ashokbugude** [comment]
Hi

I am trying to generate installer for the project .Followed the steps in
http://artoolkit.org/documentation/doku ... pplication
<http://artoolkit.org/documentation/doku.php?id=1_Getting_Started:general_deploy_application>

But getting the attached error

Pls Help

Thanks
Ashok

**Comment by ThorstenBux** [comment]
Hi,

can you please open a new issue for that. As this one is closed and I think others won't see it.

Also I cannot see any attachment can you please upload that again. 

Thanks
<img width="68" alt="screen shot 2016-03-02 at 7 05 40 pm" src="https://cloud.githubusercontent.com/assets/16772796/13761085/6ab2dcfc-ea9b-11e5-8468-bccece3bfba3.png">
(Just added that to make sure it works :) )

**Comment by ashokbugude** [comment]
Hi,

Thanks for your response.
 I have created Issue#60 in github :
https://github.com/artoolkit/arunity5/issues/60

Issue while creating Installer #60

Thanks
