### ISSUE TITLE
genTexData fails on CMYK jpg with vague error message.

### ISSUE THREAD

**Issue by GavinFowlerDAQRI** [artoolkit/arunity5#59]
As stated in subject, I tried to generate fset data using a jpg that was exported in CMYK color space and got the error "2 byte/pixel JPEG files not currently supported. Exiting." which suggests the image is in greyscale.  I suspect the logic behind that error does not account for CMYK.  Attached is an image that threw the error.  Exporting the image in RGB alleviates the problem.

Generator started at 2016-03-11 14:54:52 -0800
Select extraction level for tracking features, 0(few) <--> 4(many), [default=2]: 
MAX_THRESH  = 0.900000
MIN_THRESH  = 0.550000
SD_THRESH   = 8.000000
Select extraction level for initializing features, 0(few) <--> 3(many), [default=1]: 
SURF_FEATURE = 100
Reading JPEG file...
   Done.
Error: 2 byte/pixel JPEG files not currently supported. Exiting.

![nftgibr](https://cloud.githubusercontent.com/assets/14205906/13754820/a50d8864-e9d5-11e5-809d-e06fe7d015da.jpg)

**Comment by philip-lamb** [comment]
Fixed. https://github.com/artoolkit/artoolkit5/commit/f8bc2819b32d6ad9fc59a9e388f57be11a0304d1
