### ISSUE TITLE
Very long black screen when starting the android app exported from Unity

### ISSUE THREAD

**Issue by garryren** [artoolkit/arunity5#68]
Unity 5.3.4 +  ARtoolkit 5.3.2 

When I run the android app exported from Unity,  the app shows a black screen for a very long time before show the video camera feed properly.  If I disconnect the network of the android mobile phone then everything is fine (according to this post: http://artoolkit.org/community/forums/viewtopic.php?f=28&t=4581&hilit=slow+start)

Is this really because that the artoolkit is downloading the camera param file from google apps market?  I cannot connect to google apps market in my country,  how can I solve this problem?  (e.g. is there anyway to stop artoolkit checking camera param from servers?)

Thank you very much for the help!

**Comment by ThorstenBux** [comment]
ARToolKit tries to fetch the camera calibration from its own server specifically designed for that purpose. So it is not downloading from the google apps market and not being able to connect to google apps marked should not be an issue for you. 
The thing is for proper tracking you would need a calibration file for the camera on your device. If such a calibration is available from the ARToolKit server it gets downloaded to your device and is used during the tracking. This only happens once and is then stored on your device.
If no such calibration file is available ARToolKit checks for such a calibration file regularly. 

You can generate and upload a calibration using the calibration app for Android:
https://play.google.com/store/apps/details?id=com.artoolworks.ar.utils.calib_camera
(but as you cannot access it in your country that might be difficult)

Let me know if you have any further question

**Comment by garryren** [comment]
Thank you so much for the helping.  And yes it is difficult to get the calibration app from play store here, and the connection to the ARToolKit server can be very slow sometimes here.  I  am wondering is there anyway to stop ARToolKit downloading the calibration file from ARToolKit server?

Thank you.

**Comment by ThorstenBux** [comment]
Here I gave a starting point on how that might be done:
https://github.com/artoolkit/artoolkit5/issues/90

We'd appreciate the contribution as I don't see it coming any time soon.

Closing now as answered.

**Comment by willchamberlain** [comment]
I just came across this: even if the find-a-calibration-file behaviour cannot be changed easily, is there a way to 

- monitor the ARToolkit system state and display that status on-screen (Android)

- log a warning message like "Camera calibration file not found: searching for calibration file online: ARToolit will be unresponsive until the calibration file is downloaded."
