### ISSUE TITLE
Scripts indicate no MonoBehaviour

### ISSUE THREAD

**Issue by devyzr** [artoolkit/arunity5#80]
I've found that even after deleting, importing again and doing a re-import all the ARToolkit scripts show the 'No MonoBehaviour' error, I recently updated to 5.3.51f.

**Comment by ThorstenBux** [comment]
Which version of ARTK for Unity scripts are you using? and on which OS?

**Comment by devyzr** [comment]
Using version 5.3.2, with Windows 8.1.

**Comment by ThorstenBux** [comment]
May I ask you for a step by step description so that I can reproduce the errors. And if you have a screenshot that shows the error would also be great.

Thanks

**Comment by devyzr** [comment]
I didn't receive the notifiaction of your response at the time. Barely saw this now, my apologies.
