### ISSUE TITLE
UnityEditor.DockArea.OnGUI () NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by nandavsilva** [artoolkit/arunity5#81]
Hi!

I'm having problems with the implementation of ARToolKit with Unity when I put in the "Maximize on Play" option. It is giving the error below:

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.DockArea.OnGUI () (at C: /buildslave/unity/build/Editor/Mono/Gui/DockArea.cs: 264)
ARNativePlugin: arwStartRunningB (String, Byte [], Int32, Single, Single)
PluginFunctions: arwStartRunningB (String, Byte [], Int32, Single, Single) (at Assets / ARToolKit5-Unity / Scripts / PluginFunctions.cs: 114)
ARController: StartAR () (at Assets / ARToolKit5-Unity / Scripts / ARController.cs: 585)
ARController: Start () (at Assets / ARToolKit5-Unity / Scripts / ARController.cs: 374)

When I run without the "Maximize on Play" option, it does normally. Already updated the ARToolKit package for Unity (v. 5.3.2) and did not work. I use Unity 64-bit v. 5.3.4f1 Personal in Windows 10 (64-bit).

Can anybody help me?
Thank you!

**Comment by ThorstenBux** [comment]
Hi,

I can reproduce this error. However I cannot track it down and find anything that causes this issue. 

Does it affect you in any way other than being anoying?

**Comment by nandavsilva** [comment]
Hi,

Well, I would like to run in "Maximize on Play" when I test the scene created with ARToolKit markers in Unity, but can never in any project I created. I have created three different projects doing the basics to display an object on a marker and I always have this problem. I do exactly what the tutorial in ARToolKit site informs (http://artoolkit.org/documentation/doku.php?id=6_Unity:unity_getting_started). Just like to run maximizing screen.

Thanks!

**Comment by ThorstenBux** [comment]
Hi,

I meant I sure get the same error but other than being annoying it doesn't keep me from running the scene in fullscreen. 

So does it keep you from running the scene?

**Comment by nandavsilva** [comment]
Oh, I'm sorry.

Yes, only happens when I run in fullscreen. If I run without this option in Unity, it displays normally. And I still have to leave the Unity layout in Default to run without errors.

**Comment by OptrixAU** [comment]
DockArea exceptions are usually thrown by editor extensions (there's one on the ARController class). Not sure why an editor extension would attempt to start AR though. Perhaps there's something a little odd about how the extension is enabled / disabled.

It's an irritating issue, but thankfully not a breaking one.

**Comment by nandavsilva** [comment]
Alright, thanks!

**Comment by AndyThayer** [comment]
Thanks for the tip. I was having this same issue, but when I toggled "Maximize on Play" off I don't see the errors any more.
