### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by SanjithKanagavel** [artoolkit/arunity5#98]
I would like to re-compile the 
libARWrapper.so - for Android
ARWrapper.dll - for Windows
libARWrapper.a - for iOS

Can you please share me how to do this sir please.  @ThorstenBux

**Comment by ThorstenBux** [comment]
As for libARWrapper see here:
http://artoolkit.org/documentation/doku.php?id=4_Android:android_native
iOS:
you open the XCode project:
ARToolKit5iOS.xcodeproj
and build target ARWrapper
On Windows:
You can find the VisualStudio project in the VisualStudio directory in ARTOOLKIT5_HOME and build the target ARWrapper

**Comment by SanjithKanagavel** [comment]
Thankyou sir @ThorstenBux. You're really quick. Makes me really happy. I am creating an app using ARToolkit for Augmentive learning. Its for kids. Educating them through this technology. I would like you to show you soon sir 😄  👍

**Comment by ThorstenBux** [comment]
Sure, I'd love to see it and contribute if you like 👍

**Comment by SanjithKanagavel** [comment]
That's really great sir. Will let you know once we finish our first iteration of development :)

**Comment by SanjithKanagavel** [comment]
I have compiled it for android and ios.
But for generating dll. I can't compile ARWrapper. It depends on ARVideo to be compiled. But Movies.h file is missing for ARVideo Compilation. I guess it is in Quicktime SDK/CIncludes. But i can't find quicktime sdk on internet since mac stopped developing the sdk, Can you help me with it ? @ThorstenBux

**Comment by ThorstenBux** [comment]
Hi,
I can guide you to some documentation:
http://artoolkit.org/documentation/doku.php?id=8_Advanced_Topics:windows_building_libarvideo
http://artoolkit.org/documentation/doku.php?id=8_Advanced_Topics:build_artoolkit

However I don't know if that works as I didn't build on Windows lately.

**Comment by SanjithKanagavel** [comment]
Thanks Thorsten. I have fixed the issue with the "Movies.h". It went after i adding Quicktime SDK. I downloaded it from apple website. In the article (http://artoolkit.org/documentation/doku.php?id=8_Advanced_Topics:windows_building_libarvideo) they have mentioned that libjpeg.lib will be provided with the build. But it is not provided in master\lib\win32-i386 folder and few libs (pthreadVC2.lib,libjpeg.lib,glut32.lib) are missing. When cloned from Github Repo. Please check them.
