### ISSUE TITLE
what's the  lowest version of unity3d does arunity5 need?

### ISSUE THREAD

**Issue by dragonflyhe** [artoolkit/arunity5#99]
what's the  lowest version of unity3d does arunity5 need?
I try to unpacking ARUnity5.unitypackage to  unity3d 4.6 , I get the following errors:
Error while importing package: Couldn't create asset ProjectSettings/UnityConnectSettings.asset
Parent path, , does not exist.
how can I do?

**Comment by ThorstenBux** [comment]
Well, you should go with the latest Unity version. The personal (free) one will do.
I work with 5.3.4
